### ISSUE TITLE
Potential issue with detection probability estimation

### ISSUE THREAD

**Issue by ChloeRN** [ErlendNilsen/OpenPop_Integrated_DistSamp#10]
Noticed that when working with the nimbleDistance::dHN() version of the model, it sometimes happens that one of the p[t] (averaged detection probabilities) is estimated nearly at 1. This as a consequence of effective strip width (esw) getting estimated larger than the truncation distance (W) and `p[t] <- min(esw[t], W) / W`. 
I would think that that is something that really should not happen, and we should consider looking into what is causing this.

**Comment by ErlendNilsen** [comment]
I guess it can happen if the observation distance data are uniformely distributed?

**Comment by ChloeRN** [comment]
Several month of model development / bug fixes later, this seems to no longer be a general issue. 
There remain few  years in a handful of areas where p = 1 occurrs in the posterior, but this is relatively rare and 1 does not dominate posteriors.
