### ISSUE TITLE
0-inflation in observation distances

### ISSUE THREAD

**Issue by ChloeRN** [ErlendNilsen/OpenPop_Integrated_DistSamp#11]
Noticed that the distribution of observation distances is sometimes heavily 0-inflated. @ErlendNilsen says this may have something to do with reporting error that varies by area, i.e. in some areas people may have reported a distance of 0 even when that was not the case. 

One way of approaching/addressing this could be to make a mixture model for 0-distances (e.g. ~ Uniform(0, 5) or similar).

**Comment by ErlendNilsen** [comment]
Hmm - will that work? We assume detection probability is 1 at 0 distance, and then declining smoothly as distance increases. Not sure how we can model that if we use a mixture model?

**Comment by ChloeRN** [comment]
We'd model the detection distances reported as 0 as latent variables, assuming e.g. that they are uniformly distributed between 0 and 5 m. Not sure it will work, but it's an idea. 

Alternatively, there is also a chance that a binned detection model might be able to alleviate this somewhat (if it's actually a problem for estimation).

**Comment by ChloeRN** [comment]
Closing this, as this issue largely disappeared after we fixed the scaling errors that were in earlier versions of the model.
