### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by ErlendNilsen** [ErlendNilsen/OpenPop_Integrated_DistSamp#2]
- [x] Update data wrangling code [Erlend]
- [x] Add known-fate CMR data [Erlend]
- [x] Clean up repository [Erlend]
- [x] Update process model and detection model - with two age classes [Chloé]
- [x] Check data simulation code [Erlend]
- [x] Test run NIMBLE models on simulated data [Erlend]
- [x] Compare NIMBLE model 3b with different process models/data likelihoods [Chloé]
- [x] Check about NINA access to Sigma resources [Erlend/Chloé]
- [x] Pester IT about up-to-date WSL installation [Chloé]

**Comment by ErlendNilsen** [comment]
@ChloeRN - The update to the data wrangling code will include using the LvivingNorwayR package to access the line transect data. I think that is better than the current data download procedure.

**Comment by ChloeRN** [comment]
Added another task for comparing the "base model" to the updated versions I wrote that have a restructured process model (and age-structured data likelihood). 
Tests will have to wait until known-fate CMR data has been added though.

**Comment by ChloeRN** [comment]
We have conditional access to Sigma2 resources. In practice, we need to request access for the specific project. We also need to figure out how to use ssh (Ben says it's possible from PowerShell or using Putty, and will show me).

**Comment by ErlendNilsen** [comment]
@ChloeRN Sounds good. Perhaps I can join when Ben is showing you? I'm available Mon - Thursday next week

**Comment by ChloeRN** [comment]
@ErlendNilsen I have completed the data simulation with [https://github.com/ErlendNilsen/OpenPop_Integrated_DistSamp/commit/2fd0ccbfd6efd84736e4f8e58e5479455fb896e0]. Please double-check this makes sense.

**Comment by ChloeRN** [comment]
Test runs on simulated data have been implemented as of #27.
It remains to run this for several replicates (on a cluster).
