### ISSUE TITLE
Update map to not plot into sea areas

### ISSUE THREAD

**Issue by ChloeRN** [ErlendNilsen/OpenPop_Integrated_DistSamp#31]
The shapefile we previously used for plotting to map has municipality borders extending into the sea.
Ideally, we should plot on maps with correct land borders.

**Comment by ChloeRN** [comment]
Obtained a new shapefile from Monica, and attempted to include it in the workflow, commit https://github.com/ErlendNilsen/OpenPop_Integrated_DistSamp/commit/b29e6589873e56ce943826783b0c42fc961643f3. 

Unfortunately, something seems to be wrong with the shapefile. 
I get an error: Shape contains invalid polygons.
Additionally, there are six instances of the following warning: bounding box has potentially an invalid value range for longlat data.

The new map object is also substantially smaller than the previous one: 357 elements totaling 2.2 MB as opposed to 428 elements totaling 16.8 MB previously.

**Comment by ErlendNilsen** [comment]
@ChloeRN I can look into this tomorrow (wednesday). Don't have time today

**Comment by ChloeRN** [comment]
@ErlendNilsen great! I have set up a new branch for including the new map, it's called "include_newMap". 
(I don't think it's crucial that we have this implemented for the report, to be honest. So there is no need to rush with this one).

**Comment by ChloeRN** [comment]
@bniebuhr helped out with it and maps now have coastlines.
