### ISSUE TITLE
Complete first draft for manuscript 1

### ISSUE THREAD

**Issue by ChloeRN** [ErlendNilsen/OpenPop_Integrated_DistSamp#36]

**Comment by ChloeRN** [comment]
I can aim to write the section describing the simulation studies if needed.

**Comment by ErlendNilsen** [comment]
@ChloeRN If you want, you can have a go on ms1. If you can provide comments and input before Monday 18th, I can aim for a final version that week.

**Comment by ChloeRN** [comment]
Preprint now online: https://ecoevorxiv.org/repository/view/6499/
