### ISSUE TITLE
Make a citable version of the MS1 code (with Zenodo)

### ISSUE THREAD

**Issue by ChloeRN** [ErlendNilsen/OpenPop_Integrated_DistSamp#47]

**Comment by ErlendNilsen** [comment]
Can we also use OSF for that perhaps?

**Comment by ChloeRN** [comment]
I have checked and it looks like you can link specific GitHub repositories to OSF projects, but OSF itself has no functionality for assigning DOI's to code releases. So far, it looks like it's just Zenodo that does that. 

That does not preclude putting code, additional figures, and other material into an OSF project though if you think that would be good...
