### ISSUE TITLE
Replace 0's trick with custom half-normal distribution

### ISSUE THREAD

**Issue by ChloeRN** [ErlendNilsen/OpenPop_Integrated_DistSamp#6]
@scrogster wrote a package called [nimbleDistance](https://github.com/scrogster/nimbleDistance) which contains a custom half-normal distribution. Implementing that instead of the 0's trick may make our code more easily understandable.

**Comment by ChloeRN** [comment]
Also attempted approaches using nimbleDistance::dHR (df21141810b0f78720149aff07935b33b70ad9f9) and data augmentation (c8d7987032b314b5ae698109e2711cee4ee6b700) but neither of those are functional yet because not just the DS observation model, but also the calculation of area-averaged detection probability will need adjusting in these cases. 
Not prioritising this at the moment though.

**Comment by ErlendNilsen** [comment]
Agree - let's go with the safe! It did produce results similar / identical to the Rdistance implementation when we tested this initially though.
